apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: learn-rollout
  namespace: learn
spec:
  replicas: 3
  selector:
    matchLabels:
      app: learn  # ✅ Required selector
  template:
    metadata:
      labels:
        app: learn  # ✅ Matches selector
    spec:
      containers:
      - name: learn
        image: jkalume/hello-world:v2
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 60s}
      - setWeight: 50
      - pause: {duration: 60s}
      - setWeight: 100
      maxSurge: 1
      maxUnavailable: 0
---
apiVersion: v1
kind: Service
metadata:
  name: learn-service
  namespace: learn
spec:
  selector:
    app: learn  # ✅ Matches rollout pods
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
